### ISSUE TITLE
undefined local variable or method `password' for #<User:0x007f8bb1791cd0>

### ISSUE THREAD

**Issue by larryzhao** [nbudin/devise_cas_authenticatable#53]
After I logged in successfully against `rubycas-server`, I got this error:

```
Started GET "/users/sign_in" for 127.0.0.1 at 2012-09-18 23:48:03 +0800
Processing by Devise::CasSessionsController#new as HTML
Redirected to http://cas.mydomain.com/login?service=http%3A%2F%2F127.0.0.1%3A3000%2Fusers%2Fservice
Completed 302 Found in 0ms (ActiveRecord: 0.0ms)


Started GET "/users/service?ticket=ST-1347983282r2B9C399B1EF21A07C2" for 127.0.0.1 at 2012-09-18 23:48:03 +0800
Processing by Devise::CasSessionsController#service as HTML
  Parameters: {"ticket"=>"ST-1347983282r2B9C399B1EF21A07C2"}
  User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`username` = 'renli' LIMIT 1
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 874ms

NameError (undefined local variable or method `password' for #<User:0x007f8bb1791cd0>):
  activemodel (3.2.8) lib/active_model/attribute_methods.rb:407:in `method_missing'
  activerecord (3.2.8) lib/active_record/attribute_methods.rb:149:in `method_missing'
  devise (2.1.2) lib/devise/models/validatable.rb:54:in `password_required?'
  activesupport (3.2.8) lib/active_support/callbacks.rb:436:in `_run__3925759518155993811__validate__1547609540827105941__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:385:in `_run_validate_callbacks'
```

And if I add `attr_accessor :password` then everything looks OK.  But actually since we are authenticating against the CAS system. It's unnecessary to have the `password` field.

**Comment by zhyt1985** [comment]
In your User Model add "include Devise::Models::DatabaseAuthenticatable"
